spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/local_ct
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mikeemon
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
  application:
    name: Contact Tracer Prod
server:
  servlet:
    context-path: /contact-tracer
  port: 8090


